### PR TITLE
Update to 2.1.1

### PR DESCRIPTION
**Pull request by willirath**

### CODE REVIEW

**Comment by dfroger** [comment]
@willirath thanks for the PR!

On Windows, same error as [here](https://github.com/conda/conda-build/issues/1970)

**Comment by dfroger** [comment]
Maybe re-rendering the recipe will solve this?

**Comment by willirath** [comment]
I'll try re-rendering then.

**Comment by willirath** [comment]
Done?

**Comment by dfroger** [comment]
Great 👍
By the way, can I add you to the recipe maintainer list?

**Comment by willirath** [comment]
That was a quick PR...

> By the way, can I add you to the recipe maintainer list?

Yes, of course.

**Pull request merged**
